language: python
python:
  - "3.5"
install:
  - pip install --upgrade pip setuptools pytest
  - pip install codecov
  - pip install .
  - pip list
script:
  - python setup.py test --addopts "--cov=setuptools_antlr --cov-report html"
after_success:
    codecov
