language: python

python:
  - '3.5'

install:
- pip install --upgrade pip setuptools pytest
- pip install codecov
- pip install .
- pip list

script:
  # run unit tests
  - python setup.py test --addopts "--cov=setuptools_antlr --cov-report html"
  # build example project
  - pushd example
  - python setup.py build_antlr bdist_wheel
  - popd

after_success:
  codecov

before_deploy:
  python setup.py bdist_wheel

deploy:
  provider: releases
  api_key:
    secure: hh1po12dCGqWnf/xApPjlMcsor0uyp5DN0JSpAh2I+6O4pjSnyDKflNT48jMe1jsIADXo95mybqPzTgGECmjSg0Ey/s+HRs0ohYAeU2K5EiZjO1+pXNdrRjrrAPYrk2nXeYINYW14ht+fQtSfaPtf9HZB7Fej9soNXu640r1AmJpeBYrLq4zzcPlFVl9tWUKCzy8opBbztCkFZgj0X8EJ5VKxQsuZovp4IQoM4+ltvw/G0dKurs1Nz5mHAWfOilEcjjmxkXqmkn9ZPvAcRs9GuKJboU0FtvszovOPrs81BjZbPNSMI6fcnpiAcrqA7EbGJUZCpzA8DJp1p7sDQQnBktLBYkjyqAYm9ulVsoQkyhAnK0dekugqvE0ZVlY0OH/xsEMBwNwwAqVfSFkNtH2BXtBLY+uYGamo1nqZNmPkfbrtGzOmOcAUSe5VmBjCunFYUScAKiekzyd6IrgPh1+eJRHRYRiFuPJQqOPfb3YSAXwNIdxTE9AdcPzo3TzkBf515yT6vM6TL8vmEtpPI1+U2RwlZsTmsT46KR0Sy48LLWTid8h6mpzAFFszhYwCcxCA62HJNnZUU9OxumKlK9/7njaOUx3UkrXNSV/5MNV2zEtR3uwFclscIruaMWZ20q+zV/3es8LBl6CxONwzBROjQyBQBxQ5KpSGySh5kUsQLA=
  file_glob: true
  file: "dist/*.whl"
  skip_cleanup: true
  on:
    repo: ferraith/setuptools-antlr
    tags: true
