language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install --upgrade pip
  - python -m venv env
  - source ~/env/bin/activate
  - pip install pytest-cov coveralls
  - pip install .
  - pip list
